// Default seed data — used when Supabase is not configured (demo / local dev)
module.exports = [
  {
    id: 1,
    name: 'Nirav Patel',
    phone: '601-488-2998',
    gmail: 'Niravp1216@gmail.com',
    address: '905 Waters Edge, Brandon, Mississippi 39047',
    education: 'B.E. in Computer Science',
    last_company: 'Centene Corporation',
    last_project: 'Healthcare Cloud Migration & AI Integration',
    last_project_overview: 'Led cloud migration projects and AI-driven workflows for healthcare claims and member management, ensuring HIPAA compliance and high availability.',
    tech_stack: 'Python, AWS, Terraform, Docker, React, PostgreSQL',
    work_authorization: 'U.S. Citizen',
    visa_type: 'Citizenship (Naturalized)',
    green_card_date: '2018',
    green_card_how: 'Employer-sponsored',
    w2_c2c_preference: 'W2: $50–$85/hr, C2C: $50–$85/hr',
    ssn_last4: '1806',
    came_to_us_date: '2016',
    first_five_years_how: 'F1 → OPT → H1-B → Green Card',
    places_lived: 'Brandon, MS; previously in other US cities',
    current_location: 'Brandon, MS',
    total_companies: 3,
    marriage_date: 'Not provided',
    property_owned: 'Not provided',
    dl_name: 'Nirav Patel',
    age: '29',
    total_experience: '10+ years',
    resume_link: '',
    dl_link: '',
    github: 'https://github.com/niravp1216-tech',
    linkedin: 'https://www.linkedin.com/in/coder-48ba46251/',
    portfolio: 'https://ubiquitous-starburst-4b7914.netlify.app/',
    references: [
      { name: 'Vito Mantese', designation: 'Team Lead', company: 'Centene Corporation', email: 'Not Available', phone: '+1 314-399-9771', linkedin: 'linkedin.com/in/vito-mantese-3a7264140' },
      { name: 'Amol Basargekar', designation: 'Group Product Manager', company: 'IntegriChain', email: 'amol.basargekar@gmail.com', phone: '+1 954-555-0636', linkedin: 'linkedin.com/in/amol-basargekar-8b66aa8' },
      { name: 'Mrudula Vijayanarasimha', designation: 'Sr. Software Engineer | AI Engineer', company: 'Centene Corporation', email: 'mrudula.v1712@gmail.com', phone: '+1 585-406-2642', linkedin: 'linkedin.com/in/mrudulavijayanarasimha/' }
    ],
    created_at: '2024-01-01T00:00:00.000Z'
  },
  {
    id: 2,
    name: 'Dhaval Patel',
    phone: '+1 (980)-215-9384',
    gmail: 'dhavalkumawat76@gmail.com',
    address: '116 Mackinac Drive, Mooresville, NC 28117',
    education: 'B.E. in Computer Engineering',
    last_company: 'NBCUniversal',
    last_project: 'AI-Powered Clinical Trial Platform',
    last_project_overview: 'Led development of cloud-native microservices and AI/LLM workflows for clinical data management, patient monitoring, and regulatory compliance.',
    tech_stack: 'Python, FastAPI, AWS (Lambda, EKS, S3, DynamoDB), Terraform, Docker, LangChain, PyTorch, PostgreSQL, MongoDB, Redis',
    work_authorization: 'U.S. Citizen',
    visa_type: 'Citizenship (Naturalized)',
    green_card_date: '2019',
    green_card_how: 'Marriage to U.S. citizen',
    w2_c2c_preference: 'W2 preferred',
    ssn_last4: '6747',
    came_to_us_date: '2017',
    first_five_years_how: 'Marriage-based Green Card in 2019, Citizenship in 2025',
    places_lived: 'Mooresville, NC; previously in other US cities',
    current_location: 'Mooresville, NC',
    total_companies: 4,
    marriage_date: '2019',
    property_owned: 'Not provided',
    dl_name: 'Dhaval Patel',
    age: '33',
    total_experience: '8 years',
    resume_link: '',
    dl_link: '',
    github: 'https://github.com/niravp1216-tech',
    linkedin: 'https://www.linkedin.com/in/ai-expert-coder',
    portfolio: 'https://dhavalpatel.tech',
    references: [],
    created_at: '2024-01-01T00:00:00.000Z'
  },
  {
    id: 3,
    name: 'Foram Patel',
    phone: '(561) 342-1074',
    gmail: 'foram.patel4932@gmail.com',
    address: 'Florida',
    education: 'B.S./M.S. in Computer Science',
    last_company: 'McKinsey & Company',
    last_project: 'AI-Driven Healthcare RCM Platform',
    last_project_overview: 'Architected agentic AI and ETL pipelines for healthcare Revenue Cycle Management, cutting claim resolution time from hours to minutes using multi-agent LLM workflows and RAG systems.',
    tech_stack: 'Python, React, NestJS, FastAPI, Node.js, AWS, DynamoDB, Kubernetes, Terraform, LangChain, pgvector, Docker, Grafana',
    work_authorization: 'U.S. Citizen',
    visa_type: 'Citizenship',
    green_card_date: 'Not provided',
    green_card_how: 'Not provided',
    w2_c2c_preference: 'Not provided',
    ssn_last4: 'N/A',
    came_to_us_date: 'Not provided',
    first_five_years_how: 'Not provided',
    places_lived: 'Not provided',
    current_location: 'Florida',
    total_companies: 4,
    marriage_date: 'Not provided',
    property_owned: 'Not provided',
    dl_name: 'Foram Patel',
    age: '34',
    total_experience: '11+ years',
    resume_link: '',
    dl_link: '',
    github: 'https://github.com/foram-p',
    linkedin: 'https://www.linkedin.com/in/forampatel',
    portfolio: 'https://forampatel.dev',
    references: [],
    created_at: '2024-01-01T00:00:00.000Z'
  },
  {
    id: 4,
    name: 'Rishabh Tiwari',
    phone: 'Not provided',
    gmail: 'Rishabhstiwari1996@gmail.com',
    address: 'Not provided',
    education: 'B.Tech in Computer Science & Engineering, Rajasthan Technical University',
    last_company: 'WCG',
    last_project: 'AI-Powered Anomaly Detection & Remediation',
    last_project_overview: 'Architected secure multi-cloud infrastructure for an AI-powered anomaly detection platform using Terraform, deploying containerised microservices on AKS and OpenShift.',
    tech_stack: 'AWS, Azure, GCP, Kubernetes, Helm, Terraform, Ansible, Jenkins, GitHub Actions, ArgoCD, Datadog, Prometheus, Grafana, ELK, Python, Bash, PostgreSQL',
    work_authorization: 'Not specified',
    visa_type: 'Not specified',
    green_card_date: 'Not provided',
    green_card_how: 'Not provided',
    w2_c2c_preference: 'Not provided',
    ssn_last4: 'N/A',
    came_to_us_date: 'Not provided',
    first_five_years_how: 'Not provided',
    places_lived: 'Not provided',
    current_location: 'Not provided',
    total_companies: 5,
    marriage_date: 'Not provided',
    property_owned: 'Not provided',
    dl_name: 'Rishabh Tiwari',
    age: '0',
    total_experience: '9+ years',
    resume_link: '',
    dl_link: '',
    github: 'https://github.com/',
    linkedin: 'https://www.linkedin.com/in/',
    portfolio: '',
    references: [],
    created_at: '2024-01-01T00:00:00.000Z'
  },
  {
    id: 5,
    name: 'Ritu',
    phone: 'Not provided',
    gmail: 'Not provided',
    address: 'Not provided',
    education: 'Not specified',
    last_company: 'Centene',
    last_project: 'AI Platform Management & API Gateway',
    last_project_overview: 'Leading development of enterprise and healthcare AI & Generative AI platforms, including a centralized API management platform.',
    tech_stack: 'Python, Go, FastAPI, Flask, Django, AWS, GCP, Azure, Kubernetes, Docker, LangChain, FAISS, OpenSearch, Kafka, Airflow, Databricks, Snowflake',
    work_authorization: 'Not specified',
    visa_type: 'Not specified',
    green_card_date: 'Not provided',
    green_card_how: 'Not provided',
    w2_c2c_preference: 'Not provided',
    ssn_last4: 'N/A',
    came_to_us_date: 'Not provided',
    first_five_years_how: 'Not provided',
    places_lived: 'Not provided',
    current_location: 'Not provided',
    total_companies: 5,
    marriage_date: 'Not provided',
    property_owned: 'Not provided',
    dl_name: 'Ritu',
    age: '0',
    total_experience: '10.5 years',
    resume_link: '',
    dl_link: '',
    github: 'https://github.com/',
    linkedin: 'https://www.linkedin.com/in/',
    portfolio: '',
    references: [],
    created_at: '2024-01-01T00:00:00.000Z'
  },
  {
    id: 6,
    name: 'Hridesh Sharma',
    phone: 'Not provided',
    gmail: 'Not provided',
    address: 'Not provided',
    education: 'B.Tech in Computer Science',
    last_company: 'Brudite Private Limited',
    last_project: 'AI-Powered Slack Workflow Automation',
    last_project_overview: 'Led design and development of custom Slack applications with OAuth 2.0, RBAC, interactive components, and AI-powered workflows integrating GPT-4 and Claude via LangChain and MCP servers.',
    tech_stack: 'Python, Node.js, Go, FastAPI, Slack Bolt SDK, OAuth 2.0, LangChain, GPT-4, Claude, RAG, Vector DB, PostgreSQL, MongoDB, AWS, GCP, Terraform',
    work_authorization: 'Not specified',
    visa_type: 'Not specified',
    green_card_date: 'Not provided',
    green_card_how: 'Not provided',
    w2_c2c_preference: 'Not provided',
    ssn_last4: 'N/A',
    came_to_us_date: 'Not provided',
    first_five_years_how: 'Not provided',
    places_lived: 'Not provided',
    current_location: 'Not provided',
    total_companies: 6,
    marriage_date: 'Not provided',
    property_owned: 'Not provided',
    dl_name: 'Hridesh Sharma',
    age: '0',
    total_experience: '6+ years',
    resume_link: '',
    dl_link: '',
    github: '',
    linkedin: '',
    portfolio: '',
    references: [],
    created_at: '2024-01-01T00:00:00.000Z'
  }
];
